name: Notificacion CI

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificacion
        run: |
          curl -H "Title: Nuevo Push en main" \
               -H "Priority: default" \
               -d "Se realizo un nuevo push al repositorio en la rama main." \
               https://ntfy.sh/devops-itla
